# Generated by Django 5.2.8 on 2025-11-13 12:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='House',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=50)),
                ('district', models.CharField(blank=True, max_length=50)),
                ('community', models.CharField(blank=True, max_length=100)),
                ('address', models.CharField(blank=True, max_length=255)),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('unit_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('area', models.FloatField(help_text='建筑面积(㎡)')),
                ('rooms', models.IntegerField(default=0, help_text='室')),
                ('halls', models.IntegerField(default=0, help_text='厅')),
                ('orientation', models.CharField(blank=True, max_length=20)),
                ('floor', models.CharField(blank=True, max_length=50)),
                ('decorate', models.CharField(blank=True, max_length=50)),
                ('building_type', models.CharField(blank=True, max_length=50)),
                ('followers', models.IntegerField(default=0)),
                ('link', models.URLField(blank=True, max_length=500)),
                ('cover', models.URLField(blank=True, max_length=500)),
                ('tags', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'house',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Favorite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorites', to=settings.AUTH_USER_MODEL)),
                ('house', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorites', to='listings.house')),
            ],
            options={
                'db_table': 'favorite',
                'ordering': ['-created_at'],
                'unique_together': {('user', 'house')},
            },
        ),
    ]
