# Generated by Django 5.2.8 on 2025-12-15 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='house',
            name='latitude',
            field=models.FloatField(blank=True, help_text='纬度', null=True),
        ),
        migrations.AddField(
            model_name='house',
            name='longitude',
            field=models.FloatField(blank=True, help_text='经度', null=True),
        ),
    ]
